### ISSUE TITLE
AMP Review 1

### ISSUE THREAD

**Issue by andrewrreed** [fastforwardlabs/summarize.#9]
## Functional Review:

- [x] In **Step 2: Install Dependencies**, the spaCy model download fails silently because the command uses `!python` instead of `!python3`. This consequently results in a UI error in the Streamlit app. I forked the project and tested this simple change (python3 instead of python) and it works as expected - so should be a quick fix for you to commit.
![image](https://user-images.githubusercontent.com/23462538/134053616-64c17a11-2511-4a1d-b34c-459f1d15b542.png)

![image](https://user-images.githubusercontent.com/23462538/134053242-1a57517f-b6b5-43fd-bef7-3ac336c68d4a.png)

### Streamlit App
- [x] **Placeholder Task** - noting this here so we don't forget to populate the blog post links once available (NOTE there may be more than just these):
![image](https://user-images.githubusercontent.com/23462538/134051471-c805f827-aa13-49cc-a672-accf1690630c.png)
- [x] **"Qualitative Comparison"  --> "Quantitative Comparison":**  When a user switches from the Wikipedia dataset to the Daily News, the title of the "comparison" card should change to reflect that we now have the ability to quantify the produced summary, right?
- [x] **UX Suggestion:** Its slightly confusing to me as a first time user that the language here says: "Choose a passage to summarize." because the subsequent dropdown isn't actually passages, it's data sources.... Maybe a better instruction could be "Select a dataset" or "Select a data source to work with"
![image](https://user-images.githubusercontent.com/23462538/134052781-c419a265-b722-4d7f-9910-23142fd258df.png)

### README

- [x] **Suggestion**: The first sentence of the README makes reference to the legacy "Brief" application. Is there anything we can link to for this? I don't think the prototype is still up but maybe a blogpost or report something that helps people understand what this was?
- [x] **Edit**: I think we can remove the "fiction book chapters" since that was originally intended but didn't work out as well as expected...right?
![image](https://user-images.githubusercontent.com/23462538/134054734-7f0f88a3-f03c-4232-a2dc-e75f8a4edbe0.png)
- [x] **Placeholder Task:** reminder to update this link once the url exists
![image](https://user-images.githubusercontent.com/23462538/134055534-136293d4-e09f-44ed-a7df-bf1105766197.png)
- [x] **Edit:** This should probably be a `python3` command, right?
![image](https://user-images.githubusercontent.com/23462538/134055818-2c83f8e1-0c56-496a-a374-3f0d71953090.png)
- [x] **Edit:** I think the card in the Prototype Catalog will now say "Summarize." right?
![image](https://user-images.githubusercontent.com/23462538/134055994-412be7d3-641b-4f01-b43b-524e1ae031ce.png)

### Misc
- [x] Looks like we need to add the Apache license file to the repo
- [x] For the "references to borrowed code", it looks like one of them includes an inline comment in the code with the link to huggingfaces source. The second one looks to be missing that comment + link. Can you add that so both are referenced inline? Thanks!
- [x] Can you complete/confirm the content in columns C-F for Default Catalog metadata in [the tracking doc](https://docs.google.com/spreadsheets/d/1Z3BSQSwAoF4TIjguFVDZVXk96h9n30jscFfI0YFTjO0/edit#gid=1589786084)
- [x] Can you drop a thumbnail image into [the review doc](https://docs.google.com/document/d/1io5CRoioSefwfapcqIbG1AjmjSgTc217Z9DFprefsRE/edit#) that will appear in CML AMP Catalog?

**Comment by andrewrreed** [comment]
@melaniebeck Great job with this Streamlit app. The model wrappers for Streamlit caching is awesome and it makes for a great demo! I've documented my feedback from Review 1 here - mostly minor things that should be quick fixes. Let me know if you have any questions, thanks!

**Comment by melaniebeck** [comment]
Clsoing out this issue as all tasks have been completed -- including updating links.
